version: "3.8"

services:
  #####################
  # Service MySQL     #
  #####################
  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    expose:
      - "3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - harmoniq_network

  #####################
  # Service API       #
  #####################
  harmoniq_api:
    container_name: harmoniq_api
    build:
      context: .
      target: production
    depends_on:
      - mysql_db
    # On publie le port de l'API sur l'hôte (ex: 3333:3333)
    ports:
      - "${PORT}:${PORT}"
    # On charge toutes les variables de .env
    env_file:
      - .env
    environment:
      # Optionnel : on peut aussi redéfinir les variables ci-dessous
      # si on veut être sûrs qu’elles existent.
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: ${PORT}
      DB_CONNECTION: ${DB_CONNECTION}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    networks:
      - harmoniq_network

networks:
  harmoniq_network:

volumes:
  mysql_data:
